### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by codepunkt** [gulpjs/findup-sync#42]
This package depends on `micromatch`, which in turn depends on `braces`.
Up to version 2.3.1, `braces` has a known security vulnerability that allows regex ddos attacks.

See [https://snyk.io/vuln/npm:braces:20180219](https://snyk.io/vuln/npm:braces:20180219) for more information.

In order to mitigate this vulnerability, you should update the version of `micromatch` to the latest version and release a new version of `node-findup-sync`.

**Comment by phated** [comment]
These are bumped in master, they'll be going out at some point once I get other things wrapped up.
