### ISSUE TITLE
micromatch dependency needs to be updated

### ISSUE THREAD

**Issue by Darper** [gulpjs/findup-sync#44]
The micromatch version that is referenced in package.json is pointing to an old version of the `braces` package. This package throws an NPM audit warning if below 2.3.1. In order to avoid this audit error, version 3.1.6 or higher of micromatch is required.

If I create a PR for this, is somebody able to review? I don't understand how findup-sync works and won't have a good way of making sure that this change doesn't break anything. But in order for us to continue using commitizen this change will be required.

Thank you for your time.

**Comment by jonschlinkert** [comment]
I can review and merge. thanks

**Comment by jonschlinkert** [comment]
Actually, it looks like I can't. @phated, when was this moved to the gulpjs org? Looks like my ownership access was not preserved.

**Comment by phated** [comment]
The micromatch version is using semver and it labelled `^3.0.4`.  If you delete your package-lock.json or yarn.lock file and do a fresh install, you will have the appropriate version (that's how semver works).
