### ISSUE TITLE
Please update micromatch dep to resolve security issues

### ISSUE THREAD

**Issue by sseide** [gulpjs/findup-sync#46]
Old 3.x version of micromatch packages has some security issues. Please update to latests 4.x version to resolve them.

Current version of `findup-sync` triggers two high security warnigs with snyk security scanner.
```
✗ High severity vulnerability found in set-value
  Description: Prototype Pollution
  Info: https://snyk.io/vuln/SNYK-JS-SETVALUE-450213
  From: findup-sync@2.0.0 > micromatch@3.1.10 > snapdragon@0.8.2 > base@0.11.2 > cache-base@1.0.1 > set-value@2.0.0
  From: findup-sync@2.0.0 > micromatch@3.1.10 > braces@2.3.2 > snapdragon@0.8.2 > base@0.11.2 > cache-base@1.0.1 > set-value@2.0.0
  From: findup-sync@2.0.0 > micromatch@3.1.10 > extglob@2.0.4 > snapdragon@0.8.2 > base@0.11.2 > cache-base@1.0.1 > set-value@2.0.0
  and 7 more...

✗ High severity vulnerability found in mixin-deep
  Description: Prototype Pollution
  Info: https://snyk.io/vuln/SNYK-JS-MIXINDEEP-450212
  From: findup-sync@2.0.0 > micromatch@3.1.10 > snapdragon@0.8.2 > base@0.11.2 > mixin-deep@1.3.1
  From: findup-sync@2.0.0 > micromatch@3.1.10 > braces@2.3.2 > snapdragon@0.8.2 > base@0.11.2 > mixin-deep@1.3.1
  From: findup-sync@2.0.0 > micromatch@3.1.10 > extglob@2.0.4 > snapdragon@0.8.2 > base@0.11.2 > mixin-deep@1.3.1
  and 2 more...
```

Thanks,
Stefan Seide

**Comment by doowb** [comment]
The dependencies listed (`set-value` and `mixin-deep`) have had patch versions published. Check out [this short guide](https://gist.github.com/jonschlinkert/9a62534c4f8bc76aee6058caa3f05fd6) on how to ensure you get the latest dependencies.

**Comment by sseide** [comment]
nope - deleting entire `node_modules/` folder and `package-lock.json` does not help because version range allowed by old micromatch (or some dependency of it) prevents installation of fixed packages (`set-value`, 'mixin-deep`)

Already tested it before reporting this one. Version of `micromatch` package must be updated to get newer fixed versions of the dependencies

**Comment by doowb** [comment]
`set-value@2.0.1` and `mixin-deep@1.3.2` are patched. I just realized that the tools reporting the vulnerabilities need to be updated to include those version ranges.

**Comment by sseide** [comment]
ok, see they were just release some hours ago. 
e.g. `set-value` release only found at npm, but not at github releases right now... will send info to snyk to update their database

**Comment by sseide** [comment]
btw - `npm audit` is also very unhappy with `mocha` version and `istanbull-coveralls` too.
